export const types = Object.freeze({
  // Sync
  REWARDS_START_FETCHING: "REWARDS_START_FETCHING",
  REWARDS_STOP_FETCHING: "REWARDS_STOP_FETCHING",
  REWARDS_FILL: "REWARDS_FILL",
  REWARD_UPDATE: "REWARD_UPDATE",
  REWARDS_EMIT_ERROR: "REWARDS_EMIT_ERROR",
  // Async
  REWARDS_FETCH_ASYNC: "REWARDS_FETCH_ASYNC"
});
